# BIT[0]  : Internal error
# BIT[1]  : Encoder ABZ signal error
# BIT[2]  : Encoder UVW signal error
# BIT[3]  : Encoder counting error
# BIT[4]  : Driver temperature too high
# BIT[5]  : Driver bus voltage too high
# BIT[6]  : Driver bus voltage too low
# BIT[7]  : Driver output short-circuit
# BIT[8]  : Braking resistor temperature too high
# BIT[9] : Following error over-range
# BIT[10] : Reserved
# BIT[11] : I²T error(Overload)
# BIT[12] : Speed following error over-range
# BIT[13] : Motor temperature too high
# BIT[14] : Searching motor failed(Communication encoder)
# BIT[15] : Communication failed

uint8[16] data
